# Generated by Django 6.0.5 on 2026-08-03 02:48

import contenido.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=12, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del cargo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('funciones', models.TextField(blank=True, verbose_name='Funciones y responsabilidades')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['area__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=12, verbose_name='Estado')),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/', validators=[contenido.models.validar_archivo], verbose_name='Archivo')),
                ('nombre', models.CharField(db_index=True, max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_mime', models.CharField(blank=True, max_length=120, verbose_name='Tipo de archivo')),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Tamaño')),
                ('texto_extraido', models.TextField(blank=True, help_text='Lo que se pudo leer del archivo. Alimenta la búsqueda dentro del contenido.', verbose_name='Texto extraído')),
                ('texto_por_ocr', models.BooleanField(default=False, help_text='El OCR se equivoca. Marcarlo permite avisar de que el texto puede no ser fiel y llevar siempre al original (P6).', verbose_name='El texto se obtuvo por OCR')),
                ('enlace_externo', models.URLField(blank=True, help_text='Para video, que se enlaza y no se aloja.', verbose_name='Enlace externo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MencionEnDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('fragmento', models.TextField(blank=True, help_text='Copiado literal del documento. No se parafrasea (P6).', verbose_name='Fragmento citado')),
                ('ubicacion', models.CharField(blank=True, help_text='Página, sección o apartado.', max_length=120, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Mención en documento',
                'verbose_name_plural': 'Menciones en documentos',
                'db_table': 'mencion_en_documento',
            },
        ),
        migrations.CreateModel(
            name='Sinonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('texto', models.CharField(db_index=True, max_length=200, verbose_name='Sinónimo')),
            ],
            options={
                'verbose_name': 'Sinónimo',
                'verbose_name_plural': 'Sinónimos',
                'db_table': 'sinonimo',
                'ordering': ['texto'],
            },
        ),
        migrations.CreateModel(
            name='Termino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=12, verbose_name='Estado')),
                ('nombre', models.CharField(db_index=True, max_length=200, verbose_name='Término')),
                ('definicion', models.TextField(help_text='Una o dos frases. Es lo que se lee primero.', verbose_name='Definición')),
                ('definicion_es_publica', models.BooleanField(default=True, help_text='Si se desmarca, ni el resumen sale del área. Úsalo solo cuando la existencia misma del concepto sea sensible.', verbose_name='Definición visible para toda la empresa')),
                ('detalle', models.TextField(blank=True, help_text='Cómo se calcula, con qué formato, en qué procedimiento aparece.', verbose_name='Detalle (restringido al área)')),
                ('ejemplo', models.TextField(blank=True, help_text='Una frase real donde se use el término.', verbose_name='Ejemplo de uso')),
            ],
            options={
                'verbose_name': 'Término',
                'verbose_name_plural': 'Términos',
                'db_table': 'termino',
                'ordering': ['nombre'],
            },
        ),
    ]
