# Generated by Django 6.0.5 on 2026-08-03 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='usuarios.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='reporta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='contenido.cargo', verbose_name='Reporta a'),
        ),
        migrations.AddField(
            model_name='documento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='documento',
            name='areas',
            field=models.ManyToManyField(blank=True, help_text='Vacío = transversal, lo ve toda la empresa.', related_name='documentos', to='usuarios.area', verbose_name='Áreas dueñas'),
        ),
        migrations.AddField(
            model_name='documento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='documento',
            name='reemplaza_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazado_por', to='contenido.documento', verbose_name='Reemplaza a'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='cargos', to='contenido.documento', verbose_name='Documentos que debe leer'),
        ),
        migrations.AddField(
            model_name='mencionendocumento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='mencionendocumento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='mencionendocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menciones', to='contenido.documento', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='sinonimo',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='sinonimo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='termino',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='termino',
            name='areas',
            field=models.ManyToManyField(blank=True, help_text='Vacío = transversal, lo ve toda la empresa.', related_name='terminos', to='usuarios.area', verbose_name='Áreas dueñas'),
        ),
        migrations.AddField(
            model_name='termino',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='sinonimo',
            name='termino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinonimos', to='contenido.termino', verbose_name='Término'),
        ),
        migrations.AddField(
            model_name='mencionendocumento',
            name='termino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menciones', to='contenido.termino', verbose_name='Término'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='terminos',
            field=models.ManyToManyField(blank=True, related_name='cargos', to='contenido.termino', verbose_name='Términos que debe conocer'),
        ),
        migrations.AddIndex(
            model_name='termino',
            index=models.Index(fields=['nombre', 'estado'], name='termino_nombre_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='sinonimo',
            constraint=models.UniqueConstraint(fields=('termino', 'texto'), name='sinonimo_unico_por_termino'),
        ),
        migrations.AddConstraint(
            model_name='mencionendocumento',
            constraint=models.UniqueConstraint(fields=('termino', 'documento', 'ubicacion'), name='mencion_unica'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('nombre', 'area'), name='cargo_unico_por_area'),
        ),
    ]
