"""
Django settings for induccion project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ─────────────────────────────────────────────────────────────────────
#  Configuración por entorno  (P0.3)
# ─────────────────────────────────────────────────────────────────────
#  Ningún secreto vive en este archivo. Todos se leen de `Backend/.env`,
#  que no se versiona. La plantilla con los nombres —sin valores— está
#  en `Backend/.env.example`, que sí se versiona.
#
#  Por qué: este archivo va a git, y lo que va a git es público para
#  siempre aunque se borre después. Este proyecto ya tuvo una contraseña
#  real publicada; la historia se limpió en P0.1.
# ─────────────────────────────────────────────────────────────────────

env = environ.Env(
    DEBUG=(bool, False),                  # si falta la variable, se asume producción
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, []),
)
environ.Env.read_env(BASE_DIR / '.env')

# Sin valor por defecto a propósito: si falta SECRET_KEY, el proyecto no
# arranca. Es preferible a arrancar en silencio con una clave conocida.
SECRET_KEY = env('SECRET_KEY')

DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    'rest_framework',
    'corsheaders',

    # Propias (P0.5). Cada una con sus modelos, sus rutas y sus migraciones,
    # en vez de las 9 entidades apiladas en una sola app llamada `app1`.
    'usuarios',      # quién es cada quien, áreas, pertenencias
    'contenido',     # términos, cargos, documentos
    'busqueda',      # índice, historial, contadores
    'reportes',      # dashboard y certificados (Fase 5)
]


# ─────────────────────────────────────────────────────────────────────
#  Modelo de usuario propio  (P0.6)
# ─────────────────────────────────────────────────────────────────────
#  Esta línea es la decisión más irreversible del proyecto. Django crea las
#  tablas de permisos apuntando al modelo que esté declarado aquí en el
#  momento de la PRIMERA migración; cambiarlo después obliga a rehacer la
#  base. Se declaró con la base vacía, que es el momento más barato posible.
#
#  Absorbe el antiguo `perfildb`: cédula, teléfono y tipo de identificación
#  viven dentro del usuario, no en una tabla colgando por OneToOne.
# ─────────────────────────────────────────────────────────────────────
AUTH_USER_MODEL = 'usuarios.Usuario'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'induccion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'induccion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# La conexión completa viaja en una sola variable, DATABASE_URL, con el
# formato  motor://usuario:clave@servidor:puerto/base .
#
# Se usa una cadena única en vez de cinco claves sueltas porque es lo que
# esperan los servicios de nube, y porque cambiar de motor —o de servidor—
# pasa a ser una sola línea del `.env`. En P0.4, migrar a PostgreSQL será
# exactamente eso: cambiar `mysql://` por `postgres://`.
DATABASES = {
    'default': env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Español de Colombia. Antes estaba en `en-us` / `UTC`, lo que hacía que
# toda fecha se mostrara con cinco horas de desfase — suficiente para que
# cualquier reporte del dashboard mintiera sin que se notara (P0.9).
LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

# Las fechas se guardan en UTC y se muestran en la zona de arriba. Es lo
# correcto: si la empresa abre una sede en otro huso, nada se rompe.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ─────────────────────────────────────────────────────────────────────
#  Archivos subidos  (P0.9)
# ─────────────────────────────────────────────────────────────────────
#  Antes faltaban las dos líneas de abajo, y la consecuencia era que los
#  archivos se subían pero **no se podían abrir**. Una biblioteca donde no
#  se puede abrir el libro no es una biblioteca.
#
#  El binario va al disco; a la base solo su registro (P9).
#
#  `STORAGES` es la costura que permite mudarse a un bucket sin tocar una
#  sola línea del código que sube archivos: el día que haga falta se cambia
#  el backend de `default` y ya. Si alguien construye rutas a mano en vez de
#  usar el campo del modelo, se rompe el truco y toca reescribirlo todo.
# ─────────────────────────────────────────────────────────────────────
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Tope de lo que se acepta en una sola petición. El límite real por archivo
# vive en el modelo `Documento`; esto es el freno de la capa de arriba.
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800   # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880    # 5 MB en RAM; lo mayor va a disco


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Orígenes autorizados a llamar a la API desde el navegador.
# Nunca usar CORS_ALLOW_ALL_ORIGINS: abriría la API a cualquier página.
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')

# ─────────────────────────────────────────────────────────────────────
#  API REST  (P1.1)
# ─────────────────────────────────────────────────────────────────────
#  `DEFAULT_PERMISSION_CLASSES` es EL candado, y es lo que faltaba.
#
#  En DRF, declarar *cómo* se autentica alguien (`AUTHENTICATION_CLASSES`)
#  no impone *que tenga* que hacerlo. Son dos cosas distintas, y sin la
#  segunda la primera es decorativa. Hasta ahora la API entera estaba
#  abierta: cualquiera podía hacer `DELETE /api/perfiles/1/` desde el
#  navegador, sin sesión.
#
#  Se pone aquí y no endpoint por endpoint a propósito: así todo lo que se
#  construya de ahora en adelante **nace cerrado**, en vez de nacer abierto
#  y depender de que alguien se acuerde de protegerlo. Abrir algo pasa a
#  ser un acto deliberado y visible en el código.
# ─────────────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    # Límite de peticiones (P1.9). El del login es el que importa: sin él,
    # probar contraseñas al azar sale gratis y solo cuesta tiempo de máquina.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',        # 10 intentos por minuto y por IP
        'escritura': '120/min',
    },
    # El navegador de la API es cómodo en desarrollo y una fuga de
    # información en producción: enseña la forma de cada endpoint.
    'DEFAULT_RENDERER_CLASSES': (
        ['rest_framework.renderers.JSONRenderer',
         'rest_framework.renderers.BrowsableAPIRenderer']
        if DEBUG else
        ['rest_framework.renderers.JSONRenderer']
    ),
}


# ─────────────────────────────────────────────────────────────────────
#  Sesiones y CSRF  (P1.2)
# ─────────────────────────────────────────────────────────────────────
#  Sesiones con cookie en vez de JWT (decisión D2). El motivo es concreto:
#  un token guardado en `localStorage` es legible por cualquier JavaScript
#  que llegue a ejecutarse en la página. Una cookie `HttpOnly` no lo es —
#  el navegador la envía sola y el script no puede tocarla.
#
#  JWT solo ganaría si algún día hubiera una app móvil aparte. No la hay,
#  y el §2 no la contempla.
# ─────────────────────────────────────────────────────────────────────
SESSION_COOKIE_HTTPONLY = True          # el JavaScript no puede leerla
SESSION_COOKIE_SAMESITE = 'Lax'         # no viaja desde otros sitios
SESSION_COOKIE_AGE = 60 * 60 * 8        # 8 horas: una jornada laboral
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True       # trabajar renueva la sesión

CSRF_COOKIE_HTTPONLY = False            # el frontend SÍ debe leer esta
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')

# Sin esto el navegador no manda la cookie de sesión a la API.
CORS_ALLOW_CREDENTIALS = True

# En producción, las dos cookies solo viajan por HTTPS.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# ─────────────────────────────────────────────────────────────────────
#  Endurecimiento  (P1.9)
# ─────────────────────────────────────────────────────────────────────
#  Casi todo esto solo se activa fuera de desarrollo. Forzar HTTPS en local
#  rompería el trabajo diario sin protegerte de nada.
# ─────────────────────────────────────────────────────────────────────

# El navegador no adivina el tipo de un archivo: usa el que se le declara.
# Sin esto, un .txt con HTML dentro puede acabar ejecutándose como página.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Nadie puede meter S.A.A.I dentro de un iframe suyo para engañar a un
# usuario y hacerle pulsar cosas que no ve (clickjacking).
X_FRAME_OPTIONS = 'DENY'

# No filtrar la URL completa —que puede llevar lo que alguien buscó— a
# sitios externos al hacer clic en un enlace.
SECURE_REFERRER_POLICY = 'same-origin'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000          # un año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Detrás de nginx o de un balanceador, así es como Django se entera de
    # que la petición original venía por HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
