"""
Django settings for induccion project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ─────────────────────────────────────────────────────────────────────
#  Configuración por entorno  (P0.3)
# ─────────────────────────────────────────────────────────────────────
#  Ningún secreto vive en este archivo. Todos se leen de `Backend/.env`,
#  que no se versiona. La plantilla con los nombres —sin valores— está
#  en `Backend/.env.example`, que sí se versiona.
#
#  Por qué: este archivo va a git, y lo que va a git es público para
#  siempre aunque se borre después. Este proyecto ya tuvo una contraseña
#  real publicada; la historia se limpió en P0.1.
# ─────────────────────────────────────────────────────────────────────

env = environ.Env(
    DEBUG=(bool, False),                  # si falta la variable, se asume producción
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, []),
)
environ.Env.read_env(BASE_DIR / '.env')

# Sin valor por defecto a propósito: si falta SECRET_KEY, el proyecto no
# arranca. Es preferible a arrancar en silencio con una clave conocida.
SECRET_KEY = env('SECRET_KEY')

DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'app1.apps.App1Config',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'induccion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'induccion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# La conexión completa viaja en una sola variable, DATABASE_URL, con el
# formato  motor://usuario:clave@servidor:puerto/base .
#
# Se usa una cadena única en vez de cinco claves sueltas porque es lo que
# esperan los servicios de nube, y porque cambiar de motor —o de servidor—
# pasa a ser una sola línea del `.env`. En P0.4, migrar a PostgreSQL será
# exactamente eso: cambiar `mysql://` por `postgres://`.
DATABASES = {
    'default': env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Orígenes autorizados a llamar a la API desde el navegador.
# Nunca usar CORS_ALLOW_ALL_ORIGINS: abriría la API a cualquier página.
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
