# Generated by Django 5.1.7 on 2026-01-07 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='areadb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'Areas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='roldb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=10, verbose_name='Nombre completo')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
                'ordering': ['nombre_rol'],
            },
        ),
        migrations.CreateModel(
            name='tipo_id_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_id', models.CharField(max_length=11, verbose_name='Tipo_identificacion')),
            ],
            options={
                'verbose_name': 'Tipo de identificacion',
                'db_table': 'Tipo de identifiacion',
            },
        ),
        migrations.CreateModel(
            name='repodb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arhivo', models.FileField(upload_to='videos/%Y/%m/')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.areadb', verbose_name='ID, area')),
            ],
            options={
                'verbose_name': 'Repositorio',
                'verbose_name_plural': 'Repositorios',
            },
        ),
        migrations.CreateModel(
            name='perfildb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10, verbose_name='Numero de telefono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_id_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.tipo_id_db')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='trabajadordb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.perfildb', verbose_name='ID user')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'Trabajador',
            },
        ),
        migrations.CreateModel(
            name='evaluaciondb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=3)),
                ('id_repo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.repodb')),
                ('id_trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.trabajadordb')),
            ],
        ),
        migrations.CreateModel(
            name='userarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.areadb', verbose_name='ID, area')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.perfildb', verbose_name='Id usuario')),
            ],
            options={
                'db_table': 'Userarea',
            },
        ),
        migrations.AddField(
            model_name='trabajadordb',
            name='id_userarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userarea', verbose_name='ID user area'),
        ),
        migrations.CreateModel(
            name='userrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.roldb', verbose_name='ID roles')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.perfildb', verbose_name='ID user')),
            ],
            options={
                'db_table': 'Userrol',
            },
        ),
        migrations.AddField(
            model_name='trabajadordb',
            name='id_userrol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userrol', verbose_name='ID user rol'),
        ),
    ]
