# Generated by Django 6.0.5 on 2026-05-11 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_areadb_id_alter_evaluaciondb_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluaciondb',
            options={'verbose_name': 'Evaluacion', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.RemoveField(
            model_name='repodb',
            name='arhivo',
        ),
        migrations.AddField(
            model_name='repodb',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='repositorio/'),
        ),
        migrations.AlterField(
            model_name='evaluaciondb',
            name='id_repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.repodb'),
        ),
        migrations.AlterField(
            model_name='evaluaciondb',
            name='id_trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.trabajadordb'),
        ),
        migrations.AlterField(
            model_name='evaluaciondb',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='perfildb',
            name='tipo_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tipo_id_db'),
        ),
        migrations.AlterField(
            model_name='repodb',
            name='id_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.areadb', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='roldb',
            name='nombre_rol',
            field=models.CharField(max_length=20, verbose_name='Nombre del rol'),
        ),
        migrations.AlterField(
            model_name='tipo_id_db',
            name='tipo_id',
            field=models.CharField(max_length=11, verbose_name='Tipo de identificacion'),
        ),
        migrations.AlterField(
            model_name='trabajadordb',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.perfildb', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='trabajadordb',
            name='id_userarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userarea', verbose_name='Area del usuario'),
        ),
        migrations.AlterField(
            model_name='trabajadordb',
            name='id_userrol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userrol', verbose_name='Rol del usuario'),
        ),
        migrations.AlterField(
            model_name='userarea',
            name='id_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.areadb', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='userarea',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.perfildb', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='userrol',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.roldb', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userrol',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.perfildb', verbose_name='Usuario'),
        ),
        migrations.AlterModelTable(
            name='evaluaciondb',
            table='Evaluacion',
        ),
        migrations.AlterModelTable(
            name='repodb',
            table='Repositorio',
        ),
        migrations.AlterModelTable(
            name='tipo_id_db',
            table='TipoIdentificacion',
        ),
    ]
