# Generated by Django 6.0.5 on 2026-05-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_evaluaciondb_options_remove_repodb_arhivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_id_db',
            name='tipo_id',
            field=models.CharField(max_length=20, verbose_name='Tipo de identificacion'),
        ),
    ]
