# Generated by Django 6.0.5 on 2026-05-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_tipo_id_db_tipo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_id_db',
            name='tipo_id',
            field=models.CharField(max_length=50, verbose_name='Tipo de identificacion'),
        ),
    ]
