# Generated by Django 6.0.5 on 2026-06-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_tipo_id_db_tipo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repodb',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repodb',
            name='nombre',
            field=models.CharField(default='sin_nombre', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repodb',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
