# Generated by Django 6.0.5 on 2026-08-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaSinResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, unique=True, verbose_name='Lo que se buscó')),
                ('veces', models.PositiveIntegerField(default=1, verbose_name='Veces')),
                ('primera_vez', models.DateTimeField(auto_now_add=True, verbose_name='Primera vez')),
                ('ultima_vez', models.DateTimeField(auto_now=True, verbose_name='Última vez')),
                ('resuelto', models.BooleanField(default=False, help_text='Se marca cuando alguien crea el término o el documento que faltaba.', verbose_name='Ya documentado')),
            ],
            options={
                'verbose_name': 'Búsqueda sin resultado',
                'verbose_name_plural': 'Búsquedas sin resultado',
                'db_table': 'busqueda_sin_resultado',
                'ordering': ['-veces', '-ultima_vez'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, verbose_name='Lo que buscó')),
                ('num_resultados', models.PositiveIntegerField(default=0, verbose_name='Resultados')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Cuándo')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consulta',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ContadorTermino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veces_consultado', models.PositiveIntegerField(default=0, verbose_name='Veces consultado')),
                ('ultima_consulta', models.DateTimeField(blank=True, null=True, verbose_name='Última consulta')),
            ],
            options={
                'verbose_name': 'Contador de término',
                'verbose_name_plural': 'Contadores de términos',
                'db_table': 'contador_termino',
                'ordering': ['-veces_consultado'],
            },
        ),
    ]
