# Generated by Django 6.0.5 on 2026-08-03 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busqueda', '0001_initial'),
        ('contenido', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='contadortermino',
            name='termino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contador', to='contenido.termino', verbose_name='Término'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['usuario', '-creado_en'], name='consulta_usuario_idx'),
        ),
    ]
