# Generated by Django 6.0.5 on 2026-08-03 02:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Tipo de identificación')),
                ('abreviatura', models.CharField(help_text='CC, TI, CE, PA…', max_length=10, unique=True, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'Tipo de identificación',
                'verbose_name_plural': 'Tipos de identificación',
                'db_table': 'tipo_identificacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('numero_identificacion', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'Solo letras, números y guiones.')], verbose_name='Número de identificación')),
                ('telefono', models.CharField(blank=True, help_text='Con indicativo si aplica. Ej: +57 300 000 0000', max_length=25, verbose_name='Teléfono')),
                ('debe_cambiar_password', models.BooleanField(default=True, help_text='Se fuerza el cambio en el primer ingreso porque las credenciales se entregan.', verbose_name='Debe cambiar la contraseña')),
                ('cargo', models.ForeignKey(blank=True, help_text='El puesto en la empresa. De aquí sale lo que esta persona debería leer al entrar, sin construir rutas formativas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='contenido.cargo', verbose_name='Cargo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tipo_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.tipoidentificacion', verbose_name='Tipo de identificación')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['first_name', 'last_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre del área')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('jefe', models.OneToOneField(blank=True, help_text='Solo un administrador puede nombrarlo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Jefe del área')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'area',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='usuarios.area', verbose_name='Área')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Área del usuario',
                'verbose_name_plural': 'Áreas de los usuarios',
                'db_table': 'usuario_area',
                'ordering': ['usuario', 'area'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'area'), name='usuario_area_unica')],
            },
        ),
    ]
